---
markdown: kramdown
highlighter: rouge
title: Andrea
tagline: Barraza-Urbina
description: Living in Permanent Beta
url: http://apbarraza.com
baseurl: ""
author:
  name: Andrea Barraza
  url: https://twitter.com/apbarraza

#paginate: 5
#paginate_path: '/blog/page:num'
#sidebar_blog_link: '/blog'


exclude:
- README.md
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-paginate

sidebar_home_link: true
theme_colors:
  sidebar-bg-color: "#4DA9E9"
  sidebar-fg-color: "#FFFFFF"
  link-color: "#000000"
sidebar-sticky: true
layout-reverse: false
remote_theme: fongandrew/hydeout
google_analytics: ''
disqus:
  shortname: ''
theme: jekyll-theme-hydeout
